language: python

python:
  - 3.6

install:
  # Install our awesome package
  - pip install .

  # Upgrade test runner
  - pip install --upgrade pytest

  # Measures code coverage
  - pip install coverage

  # Extension for pytest to help run coverage
  - pip install coverage pytest-cov

  # Coverage report uploader
  - pip install codecov

script:
  - pytest --cov

after_success:
  - codecov
